### ISSUE TITLE
[Crash] No Mixin host service is available with latest Satchels (1.0.3)

### ISSUE THREAD

**Issue by Desempregago** [makamys/Satchels#3]
```[01:29:43] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:113)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:106)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:77)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.newInstance(Class.java:442)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 8 more
[01:29:43] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.ArrayIndexOutOfBoundsException: 5
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[01:29:43] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
```

**Comment by makamys** [comment]
Fixed now, thanks!
